version: '3'

services:
  zookeeper-kafka:
    # image: confluentinc/cp-zookeeper:latest
    image: nguyenngochuy/zookeeper:latest

    container_name: zookeeper-isofh
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ['CMD', 'date']
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    # image: wurstmeister/kafka:latest
    image: nguyenngochuy/kafka:latest

    restart: always
    container_name: kafka-isofh
    depends_on:
      - zookeeper-kafka
    ports:
      - '19092:9092'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-kafka:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:39092,HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:39092,HOST://10.0.0.55:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      # KAFKA_CREATE_TOPICS: 'test:1:1'
    healthcheck:
      test:
        [
          'CMD',
          '/opt/kafka/bin/kafka-topics.sh',
          '--list',
          '--bootstrap-server',
          'localhost:9092',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-ui:
    container_name: kafka-ui-isofh
    # image: provectuslabs/kafka-ui:latest
    image: nguyenngochuy/kafka-ui:latest

    ports:
      - "18080:8080"
    depends_on:
      - zookeeper-kafka
      - kafka
    environment:
      AUTH_TYPE: "LOGIN_FORM"
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: abcd@9876#1234
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:39092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper-kafka:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997