version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Huynn@9890#!

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 2888:2888
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Huynn@9890#!
      ME_CONFIG_MONGODB_URL: mongodb://root:Huynn@9890#!@mongo:27017/