version: "3.9"
services:
  mongodb:
    image: mongo:6.0.5
    container_name: mongo-db-rasa
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ivirse
      MONGO_INITDB_ROOT_PASSWORD: ivirse@u7XZI=7P6jXZ
    volumes:
      - "/home/isofh/server/mongodb/config/mongod.conf:/data/configdb/mongod.conf"
      # - "/home/isofh/server/mongodb/data:/data/db"
      - "/home/isofh/server/mongodb/log:/var/log/mongodb"
      # - "./config/mongod.conf:/data/configdb/mongod.conf:ro"
      - "/home/isofh/server/mongodb/data:/data/db"
      # - "log:/var/log/mongodb"
    restart: always
volumes:
  log: null
