version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "AdMiN@2023#SysTeM"
      MONGO_INITDB_DATABASE: admin
    # command: --config /etc/mongod.conf
    ports:
      - "27017:27017"
    volumes:
      - /home/isofh/data/mongo:/data/db
      # - /path/to/your/mongod.conf:/etc/mongod.conf
  # mongo-express:
  #   image: mongo-express:latest
  #   restart: always
  #   container_name: mongo-express
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: AdMiN@2023!#*SysTeM
  #     ME_CONFIG_MONGODB_URL: mongodb://root:AdMiN@2023!#*SysTeM@mongo:27017/