version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Huynn@9890#!
    ports:
      - 27017:27017
    volumes:
      - ./home/isofh/data/mongo:/data/db
  # mongo-express:
  #   image: mongo-express:latest
  #   restart: always
  #   container_name: mongo-express
  #   ports:
  #     - 28888:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: Huynn@9890#!
  #     ME_CONFIG_MONGODB_URL: mongodb://root:Huynn@9890#!@mongo:27017/